"use client";

import { Dialog } from "@jects/jds";
import type { CheckinDialogContent } from "@/lib/checkin";

type CheckinErrorDialogProps = {
  content: CheckinDialogContent | null;
  onClose: () => void;
};

function connectAccessibilityLabels(dialog: HTMLDivElement | null) {
  if (!dialog) return;

  // JDS 0.4.0 renders h2/p without the IDs generated by its Radix Dialog.
  const titleId = dialog.getAttribute("aria-labelledby");
  const descriptionId = dialog.getAttribute("aria-describedby");
  const title = dialog.querySelector("h2");
  const description = dialog.querySelector("p");

  if (titleId && title) title.id = titleId;
  if (descriptionId && description) description.id = descriptionId;
}

export function CheckinErrorDialog({
  content,
  onClose,
}: CheckinErrorDialogProps) {
  return (
    <Dialog
      ref={connectAccessibilityLabels}
      open={content !== null}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
      header={content?.title ?? ""}
      body={content?.body ?? ""}
      isButtonStretched
      primaryAction={{
        children: "확인",
        onClick: onClose,
        hierarchy: "primary",
      }}
    />
  );
}
