"use client";

import Image from "next/image";
import { FormEvent, useState } from "react";
import { BlockButton, Dialog, TextField, Toast, useToast } from "@jects/jds";
import { submitCheckin } from "@/lib/checkin";
import type { CheckinEvent } from "@/lib/event";
import { Spinner } from "./spinner";

type FieldErrors = Partial<Record<"name" | "phone", string>>;
const SUBMISSION_TIMEOUT_MS = 5_000;
const normalizePhone = (value: string) =>
  value.replace(/[^0-9]/g, "").slice(0, 11);

function connectDialogAccessibilityLabels(dialog: HTMLDivElement | null) {
  if (!dialog) return;

  // JDS renders visible h2/p elements without connecting the IDs generated by
  // its underlying Radix Dialog. Attach them so assistive technology can use
  // the visible title and description.
  const titleId = dialog.getAttribute("aria-labelledby");
  const descriptionId = dialog.getAttribute("aria-describedby");
  const title = dialog.querySelector("h2");
  const description = dialog.querySelector("p");

  if (titleId && title) title.id = titleId;
  if (descriptionId && description) description.id = descriptionId;
}

function validate(name: string, phone: string): FieldErrors {
  const errors: FieldErrors = {};
  if (!name.trim()) errors.name = "이름을 입력해주세요.";
  else if (name.trim().length < 2)
    errors.name = "이름을 두 글자 이상 입력해주세요.";
  const phoneNumbers = normalizePhone(phone);
  if (!phoneNumbers) errors.phone = "연락처를 입력해주세요.";
  else if (!/^01[016789]\d{7,8}$/.test(phoneNumbers)) {
    errors.phone = "올바른 휴대전화 번호를 입력해주세요.";
  }
  return errors;
}

type CheckinFormProps = {
  event: CheckinEvent;
  onComplete: () => void;
  onAlreadyCheckedIn: () => void;
};

export function CheckinForm({
  event,
  onComplete,
  onAlreadyCheckedIn,
}: CheckinFormProps) {
  const { toast } = useToast();
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [errors, setErrors] = useState<FieldErrors>({});
  const [isPending, setIsPending] = useState(false);
  const [failureMessage, setFailureMessage] = useState<string | null>(null);
  const [showDelayToast, setShowDelayToast] = useState(false);

  const handleSubmit = async (formEvent: FormEvent<HTMLFormElement>) => {
    formEvent.preventDefault();
    if (isPending) return;
    const nextErrors = validate(name, phone);
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) {
      return;
    }

    setIsPending(true);
    setShowDelayToast(false);
    const controller = new AbortController();
    let didTimeout = false;
    const timeout = window.setTimeout(() => {
      didTimeout = true;
      setShowDelayToast(true);
      controller.abort();
    }, SUBMISSION_TIMEOUT_MS);

    try {
      const result = await submitCheckin(event.id, event.submissionEndpoint, {
        name: name.trim(),
        phone: normalizePhone(phone),
      }, controller.signal);
      if (result.status === "success") {
        toast.positive("체크인이 완료되었습니다.");
        onComplete();
      } else if (result.status === "duplicate") {
        onAlreadyCheckedIn();
      } else if (result.status === "invalid-event") {
        setFailureMessage("체크인할 수 없는 행사입니다.");
      } else {
        setFailureMessage("잠시 후 다시 시도해주세요.");
      }
    } catch {
      if (!didTimeout) {
        setFailureMessage("잠시 후 다시 시도해주세요.");
      }
    } finally {
      window.clearTimeout(timeout);
      setIsPending(false);
    }
  };

  return (
    <>
      <form className="checkin-form" onSubmit={handleSubmit} noValidate>
        <div className="checkin-form__fields">
          <TextField
            name="name"
            label="이름"
            placeholder="김젝트"
            value={name}
            onChange={(event) => {
              setName(event.target.value);
              if (errors.name)
                setErrors((current) => ({ ...current, name: undefined }));
            }}
            validation={errors.name ? "error" : "none"}
            helperText={errors.name}
            autoComplete="name"
            disabled={isPending}
            required
          />
          <TextField
            name="phone"
            type="tel"
            inputMode="numeric"
            label="휴대폰 번호"
            placeholder="01012345678"
            value={phone}
            onChange={(event) => {
              setPhone(normalizePhone(event.target.value));
              if (errors.phone)
                setErrors((current) => ({ ...current, phone: undefined }));
            }}
            validation={errors.phone ? "error" : "none"}
            helperText={errors.phone}
            autoComplete="tel"
            disabled={isPending}
            required
          />
        </div>
        <BlockButton.Basic
          type="submit"
          size="md"
          hierarchy="primary"
          disabled={isPending}
        >
          <span className="checkin-submit__content">
            제출하기
            {isPending && (
              <Spinner size={16} strokeWidth={2} aria-hidden="true" role={undefined} />
            )}
          </span>
        </BlockButton.Basic>
      </form>
      {showDelayToast && (
        <div className="submission-delay-toast">
          <Toast.Basic
            id="submission-delay"
            title={
              <span className="submission-delay-toast__message">
                <Image src="/caution.svg" width={16} height={16} alt="" />
                <span>응답이 지연되고 있습니다. 다시 시도해주세요.</span>
              </span>
            }
            onRemove={() => setShowDelayToast(false)}
          />
        </div>
      )}
      <Dialog
        ref={connectDialogAccessibilityLabels}
        open={failureMessage !== null}
        onOpenChange={(open) => {
          if (!open) setFailureMessage(null);
        }}
        header="체크인에 실패했습니다"
        body={failureMessage ?? ""}
        isButtonStretched={true}
        primaryAction={{
          children: "확인",
          onClick: () => setFailureMessage(null),
          hierarchy: "primary",
        }}
      />
    </>
  );
}
