"use client";

import { Dialog } from "@jects/jds";

type FailureDialogProps = {
  message: string | null;
  onClose: () => void;
};

function connectAccessibilityLabels(dialog: HTMLDivElement | null) {
  if (!dialog) return;

  // JDS 0.4.0 renders h2/p without the IDs generated by its Radix Dialog.
  const titleId = dialog.getAttribute("aria-labelledby");
  const descriptionId = dialog.getAttribute("aria-describedby");
  const title = dialog.querySelector("h2");
  const description = dialog.querySelector("p");

  if (titleId && title) title.id = titleId;
  if (descriptionId && description) description.id = descriptionId;
}

export function FailureDialog({ message, onClose }: FailureDialogProps) {
  return (
    <Dialog
      ref={connectAccessibilityLabels}
      open={message !== null}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
      header="체크인에 실패했습니다"
      body={message ?? ""}
      isButtonStretched
      primaryAction={{
        children: "확인",
        onClick: onClose,
        hierarchy: "primary",
      }}
    />
  );
}
